# DO NOT EDIT
# This file has been generated by
# $ ./tools/sources.sh tools/sources-R4.1.lst

{pkgs}:
{
  # Head of branch R4.1 of repository github.com/Juniper/contrail-build at 2018-11-26 15:55:59
  build = pkgs.fetchFromGitHub {
    name = "build";
    owner = "Juniper";
    repo = "contrail-build";
    rev = "b3e213e479619978b033b2006bb1be55e268e216";
    sha256 = "0cr3wc8s1yf2827nwmlc8jw4wdi4hw0nchq43rnpgpkmw04j9abh";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-controller at 2018-11-26 15:56:01
  controller = pkgs.fetchFromGitHub {
    name = "controller";
    owner = "Juniper";
    repo = "contrail-controller";
    rev = "eb57dcfa0d436abf0f3a49e97e612ff70ebef251";
    sha256 = "1jsl0157a737309mihn0bm4wr29kqbxhxd193hh31vcc01aagxla";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-generateds at 2018-11-26 15:56:15
  generateds = pkgs.fetchFromGitHub {
    name = "generateds";
    owner = "Juniper";
    repo = "contrail-generateds";
    rev = "661a579cedd0ec6de8cb8e55e9f15c8d90195837";
    sha256 = "1hmi5164r8j00r5s4q5b4yi69vnbxvy58176aw10h0pf9n8y04yk";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-neutron-plugin at 2018-11-26 15:56:20
  neutronPlugin = pkgs.fetchFromGitHub {
    name = "neutronPlugin";
    owner = "Juniper";
    repo = "contrail-neutron-plugin";
    rev = "40ad78c635a28f24ef0fcf1a89f5817a59507ded";
    sha256 = "1f8hi1z860b95jcdjj2ylnn41sd76cz44v7bhjwh2nfmi09kqryf";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-sandesh at 2018-11-26 15:56:21
  sandesh = pkgs.fetchFromGitHub {
    name = "sandesh";
    owner = "Juniper";
    repo = "contrail-sandesh";
    rev = "daf2174b2126f5c065e4b17202ddf2e080de69ae";
    sha256 = "1ggfx9avmj460s7a09ip2whzy8aphapiy87m9bxwb5spim0ifp6y";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-third-party at 2018-11-26 15:56:23
  thirdParty = pkgs.fetchFromGitHub {
    name = "thirdParty";
    owner = "Juniper";
    repo = "contrail-third-party";
    rev = "ddc576e9c037e1ccc0e297a64ce92e4bedf95d63";
    sha256 = "07vq2gcqj3l450jj8fvz5zzslj8dxqpiyb3fs4ncqb2ayjaqxzlc";
  };
  # Head of branch R4.1 of repository github.com/Juniper/contrail-vrouter at 2018-11-26 15:56:25
  vrouter = pkgs.fetchFromGitHub {
    name = "vrouter";
    owner = "Juniper";
    repo = "contrail-vrouter";
    rev = "79f19d1fbc8d60cdc119d5379c106356439680fa";
    sha256 = "0wmyc26xkjm0cvyfgpwkgfabjpkipxpngy3wsgis7djw6vik3c73";
  };
}
